sudo: required
services:
    - docker
before_install:
    - docker build -t docker-test -f Dockerfile.dev .
script:
    - docker run -e CI=true docker-test npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-testing"
    environment: "DockerTesting-env"
    bucket_name: "elasticbeanstalk-us-east-2-615499284044"
    bucket_path: "docker-testing"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY